import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { Code2, Cpu, Download, CheckCircle2, Terminal, Layers, Palette, FileJson, ArrowRight, Loader2, Folder, FileCode, Package, Play } from 'lucide-react';
import Header from '../components/Header';
import { useAuth } from '../context/AuthContext';
import { db } from '../lib/firebase';
import { doc, getDoc, updateDoc } from 'firebase/firestore';
import { MobileProject } from '../types';
import { GoogleGenAI } from "@google/genai";
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export default function StitchPage() {
  const { projectId } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [project, setProject] = useState<MobileProject | null>(null);
  const [loading, setLoading] = useState(true);
  const [buildingStep, setBuildingStep] = useState<string | null>(null);
  const [generatedFiles, setGeneratedFiles] = useState<Record<string, string>>({});
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [isZipping, setIsZipping] = useState(false);

  useEffect(() => {
    const fetchProject = async () => {
      if (!user || !projectId) return;
      try {
        const docRef = doc(db, 'projects', projectId);
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) {
          const data = docSnap.data() as MobileProject;
          setProject({ id: docSnap.id, ...data });
          if (data.stitch?.files) {
            setGeneratedFiles(data.stitch.files);
            // Select the first file by default
            const files = Object.keys(data.stitch.files);
            if (files.length > 0) {
              setSelectedFile(files.includes('App.tsx') ? 'App.tsx' : files[0]);
            }
          }
        }
      } catch (error) {
        console.error("Error fetching project:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchProject();
  }, [user, projectId]);

  const runStitch = async () => {
    if (!project) return;
    setBuildingStep('Initialisation du moteur Stitch...');
    setGeneratedFiles({});
    
    try {
      // 1. Generate Project Structure & Files
      setBuildingStep('Architecture du projet Expo...');
      
      const prompt = `
        Tu es un expert React Native / Expo.
        Génère les fichiers essentiels pour une application mobile nommée "${project.name}" dans la niche "${project.niche}".
        
        Fichiers requis :
        1. package.json (avec les dépendances essentielles : expo, react, react-native, expo-router, etc.)
        2. app.json (configuration Expo)
        3. App.tsx (Point d'entrée avec NavigationContainer si besoin ou Expo Router)
        4. src/theme.ts (Couleurs et styles basés sur la niche)
        5. src/screens/HomeScreen.tsx (Écran d'accueil complet et stylisé)
        
        Renvoie UNIQUEMENT un objet JSON où les clés sont les chemins des fichiers et les valeurs sont le contenu du code.
        Exemple:
        {
          "package.json": "...",
          "app.json": "...",
          "App.tsx": "...",
          "src/theme.ts": "...",
          "src/screens/HomeScreen.tsx": "..."
        }
      `;

      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: { responseMimeType: "application/json" }
      });

      const files = JSON.parse(response.text || "{}");
      setGeneratedFiles(files);
      setSelectedFile('App.tsx');

      // Save to Firestore
      setBuildingStep('Sauvegarde du code...');
      const docRef = doc(db, 'projects', project.id);
      await updateDoc(docRef, {
        stitch: {
          status: 'completed',
          lastRun: new Date().toISOString(),
          files: files
        }
      });

      // Update local state
      setProject(prev => prev ? {
        ...prev,
        stitch: {
          status: 'completed',
          lastRun: new Date().toISOString(),
          files: files
        }
      } : null);

      setBuildingStep(null);

    } catch (error) {
      console.error("Stitch Error:", error);
      setBuildingStep(null);
      alert("Erreur lors de la génération du code.");
    }
  };

  const downloadProject = async () => {
    if (Object.keys(generatedFiles).length === 0) return;
    setIsZipping(true);
    try {
      const zip = new JSZip();
      
      // Add generated files
      Object.entries(generatedFiles).forEach(([path, content]) => {
        zip.file(path, content);
      });

      // Add a simple README
      zip.file("README.md", `# ${project?.name}\n\nGenerated by AppStoreOS Stitch.\n\n## Setup\n\n1. Run \`npm install\`\n2. Run \`npx expo start\``);

      const content = await zip.generateAsync({ type: "blob" });
      saveAs(content, `${project?.name.toLowerCase().replace(/\s+/g, '-')}-starter.zip`);
    } catch (error) {
      console.error("Zip Error:", error);
      alert("Erreur lors de la création du ZIP.");
    } finally {
      setIsZipping(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#050505] flex items-center justify-center">
        <Loader2 className="animate-spin text-blue-500" size={48} />
      </div>
    );
  }

  if (!project) return null;

  return (
    <div className="min-h-screen bg-[#050505] text-white font-sans flex flex-col">
      <Header />

      <main className="flex-1 flex flex-col pt-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto w-full">
        {/* Header Section */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2 py-1 rounded-lg bg-blue-500/10 text-[10px] font-bold text-blue-400 uppercase tracking-widest border border-blue-500/20">
                Build Phase
              </span>
              <span className="text-gray-500 text-sm">/</span>
              <span className="text-gray-400 text-sm font-medium">{project.name}</span>
            </div>
            <h1 className="text-3xl font-bold flex items-center gap-3">
              <Cpu className="text-blue-500" /> Stitch Engine
            </h1>
            <p className="text-gray-400 mt-2 max-w-xl">
              Générez le code source complet de votre application React Native (Expo) en un clic.
            </p>
          </div>

          <div className="flex gap-3">
            {!buildingStep && Object.keys(generatedFiles).length > 0 && (
              <button
                onClick={downloadProject}
                disabled={isZipping}
                className="flex items-center gap-2 px-4 py-2 bg-[#141418] border border-white/10 hover:bg-white/5 text-white rounded-xl font-bold transition-all"
              >
                {isZipping ? <Loader2 className="animate-spin" size={18} /> : <Download size={18} />}
                Télécharger le ZIP
              </button>
            )}
            <button
              onClick={runStitch}
              disabled={!!buildingStep}
              className={`flex items-center gap-2 px-6 py-2 rounded-xl font-bold transition-all ${
                buildingStep 
                  ? 'bg-blue-500/20 text-blue-300 cursor-not-allowed'
                  : 'bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-500/20'
              }`}
            >
              {buildingStep ? (
                <>
                  <Loader2 className="animate-spin" size={18} />
                  {buildingStep}
                </>
              ) : (
                <>
                  <Play size={18} fill="currentColor" />
                  {Object.keys(generatedFiles).length > 0 ? 'Régénérer le Code' : 'Générer le Code'}
                </>
              )}
            </button>
          </div>
        </div>

        {/* Main Content Area */}
        <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-6 mb-8 min-h-[600px]">
          
          {/* Sidebar: File Explorer */}
          <div className="lg:col-span-3 bg-[#141418] border border-white/5 rounded-2xl overflow-hidden flex flex-col">
            <div className="p-4 border-b border-white/5 bg-white/5">
              <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest flex items-center gap-2">
                <Folder size={14} /> Structure du Projet
              </h3>
            </div>
            <div className="flex-1 overflow-y-auto p-2 space-y-1">
              {Object.keys(generatedFiles).length > 0 ? (
                Object.keys(generatedFiles).sort().map((fileName) => (
                  <button
                    key={fileName}
                    onClick={() => setSelectedFile(fileName)}
                    className={`w-full text-left px-3 py-2 rounded-lg text-sm font-mono flex items-center gap-2 transition-colors ${
                      selectedFile === fileName 
                        ? 'bg-blue-500/20 text-blue-400 border border-blue-500/30' 
                        : 'text-gray-400 hover:bg-white/5 hover:text-white'
                    }`}
                  >
                    {fileName.endsWith('.json') ? <FileJson size={14} /> : <FileCode size={14} />}
                    <span className="truncate">{fileName}</span>
                  </button>
                ))
              ) : (
                <div className="text-center py-10 text-gray-600 text-sm px-4">
                  <Package size={32} className="mx-auto mb-3 opacity-20" />
                  <p>Aucun fichier généré.</p>
                  <p className="text-xs mt-2">Lancez Stitch pour créer l'architecture.</p>
                </div>
              )}
            </div>
          </div>

          {/* Code Editor View */}
          <div className="lg:col-span-9 bg-[#141418] border border-white/5 rounded-2xl overflow-hidden flex flex-col relative">
            {selectedFile ? (
              <>
                <div className="flex items-center justify-between px-4 py-3 border-b border-white/5 bg-[#0A0A0C]">
                  <div className="flex items-center gap-2 text-sm text-gray-400 font-mono">
                    <span className="text-blue-500">{selectedFile}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <button 
                      onClick={() => {
                        navigator.clipboard.writeText(generatedFiles[selectedFile]);
                        alert("Copié !");
                      }}
                      className="p-1.5 hover:bg-white/10 rounded-lg text-gray-500 hover:text-white transition-colors"
                      title="Copier le code"
                    >
                      <CheckCircle2 size={16} />
                    </button>
                  </div>
                </div>
                <div className="flex-1 overflow-auto bg-[#0A0A0C] p-4">
                  <pre className="font-mono text-sm text-gray-300 leading-relaxed">
                    <code>{generatedFiles[selectedFile]}</code>
                  </pre>
                </div>
              </>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-gray-600 bg-[#0A0A0C]">
                <Code2 size={64} className="mb-4 opacity-20" />
                <p className="text-lg font-medium">Prêt à coder</p>
                <p className="text-sm max-w-md text-center mt-2 px-4">
                  Stitch utilise l'IA pour générer une base de code React Native propre et modulaire, adaptée à votre niche "{project.niche}".
                </p>
              </div>
            )}
            
            {/* Loading Overlay */}
            {buildingStep && (
              <div className="absolute inset-0 bg-[#0A0A0C]/90 backdrop-blur-sm flex flex-col items-center justify-center z-20">
                <div className="relative">
                  <div className="w-16 h-16 border-4 border-blue-500/30 border-t-blue-500 rounded-full animate-spin mb-4"></div>
                  <div className="absolute inset-0 flex items-center justify-center">
                    <Cpu size={24} className="text-blue-500 animate-pulse" />
                  </div>
                </div>
                <h3 className="text-xl font-bold text-white mb-2">Stitch est au travail</h3>
                <p className="text-blue-400 font-mono text-sm animate-pulse">{buildingStep}</p>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
